export const en = {
  enter_register_mobile_no: 'REGISTER MOBILE NO.',
  enter_mobile_no: 'MOBILE NO.',
  mobile_no_placeholder: 'Enter register mobile no.',
  enter_password: 'PASSWORD',
  password_placeholder: 'Enter password',
  remember_me: 'Remember Me',
  login: 'LOGIN',
  forgot_your_password: 'Forgot your password?',
  or: 'OR',
  sign_up: 'SIGN UP',
  home: 'HOME',
  enter_confirm_password: 'CONFIRM PASSWORD',
  confirm_password_placeholder: 'Enter confirm password',
  enter_otp: 'OTP',
  otp_placeholder: 'Enter otpp',
  back: 'BACK',
  reset_password: 'RESET PASSWORD',
  enter_first_name: 'FIRST NAME',
  first_name_placeholder: 'Enter first name',
  enter_last_name: 'LAST NAME',
  last_name_placeholder: 'Enter last name',
  enter_email_id: 'EMAIL ID',
  email_placeholder: 'Enter email id',
  register: 'REGISTER',
  change_password: 'CHANGE PASSWORD',
  enter_address1: 'ADDRESS *',
  address1_placeholder: 'Enter address',
  enter_area: 'AREA *',
  area_placeholder: 'Enter area name',
  enter_city: 'CITY *',
  city_placeholder: 'Enter city name',
  enter_state: 'STATE *',
  state_placeholder: 'Enter state',
  enter_pincode: 'PINCODE *',
  pincode_placeholder: 'Enter pincode',
  add_address: 'ADD ADDRESS',
  change_address: 'CHANGE ADDRESS',
  enter_quantity: 'QUANTITY',
  quantity_placeholder: 'Enter quantity',
  product_unit: 'PRODUCT UNIT',
  otp_placeholder: 'Enter otp',
  search_product_placeholder: 'Enter text here to search products',
  coupon_code_placeholder: 'Enter coupone code here',
};
